---
apiVersion: v1
kind: Pod
metadata:
  name: counter-api
  labels:
    app: counter-api
    version: 1.0.0
spec:
  containers:
    - name: counter-api
      image: khaosdoctor/node-counter-api
      env:
        - name: PORT
          value: '8080'
        - name: COUNTER_DIRECTORY
          value: '/etc/counter-volume'
      ports:
        - name: porta-api
          containerPort: 8080
      volumeMounts:
        - mountPath: '/etc/counter-volume'
          name: counter-volume

  volumes:
    - name: counter-volume
      emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: counter-svc
spec:
  selector:
    app: counter-api
  ports:
    - protocol: TCP
      port: 8085
      targetPort: porta-api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: '/counter'
            backend:
              service:
                name: counter-svc
                port:
                  number: 8085
